#+title: JavaScript components
#+PROPERTY: header-args :tangle main.js
#+auto_tangle:y

* Preamble
This directory contains the JavaScript components of this AGS configuration. They serve as the backbones of the widgets, which will be fleshed out appearance-wise by the [[file:../scss/README.org][SCSS components]] of this configuration.

This document also serves as a literate configuration. This means that [[file:./main.js][main.js]] is tangled from this document, making the documentation and the code one and the same. Any changes to be made to =main.js= is to be made here; otherwise, it will be overwritten if this document is tangled (which it is set to automatically do so on save, assuming you have =auto-tangle= installed on your Emacs).

* The =main.js=
The =main.js= file is responsible for starting up the different windows in this AGS configuration. Therefore, it is imperative that any new windows is added to this file to be started up.

** Imports
#+begin_src js
import Bar from './windows/bar/main.js';
import Dashboard from './windows/dashboard/main.js';
import Notifications from './windows/notifications/main.js';
#+end_src

* Spawn windows for each monitor
#+begin_src js
const windows = () => [
  forMonitors(Bar),
  forMonitors(Notifications),
  Dashboard();
];
#+end_src

* Export
#+begin_src js
export default {
  windows: windows().flat(1),
  maxStreamVolume: 1.05,
  cacheNotificationActions: true,
  closeWindowDelay: {
    'quicksettings': options.transition.value,
    'dashboard': options.transition.value,
  },
};
#+end_src
