#+title: AGS configurations
#+auto_tangle:y

* The =config.js=
AGS will always read off of any =config.js= file located in the configuration directory (=~/.config/ags= normally, but by the power of Home-manager, we have it in this directory). We can achieve modularity in our configurations by leveraging JavaScript's importing capabilities, which allows you to import objects exported by other files.

Therefore, our main =config.js= will simply verify whether or not the version of AGS currently installed is the same as what is expected for this configuration. This is what [[https://github.com/Aylur/dotfiles/blob/main/ags/config.js][Aylur does]], and I'm assuming this is done to avoid unexpected behaviours due to the fact that AGS is still in its beta.

#+begin_src js :tangle config.js
import { readFile } from 'resource:///com/github/Aylur/ags/utils.js';
import App from 'resource:///com/github/Aylur/ags/app.js';
const pkgjson = JSON.parse(readFile(App.configDir + '/package.json'));

const v = {
    ags: `v${pkg.version}`,
    expected: `v${pkgjson.version}`,
};

function mismatch() {
    print(`my config expects ${v.expected}, but your ags is ${v.ags}`);
    App.connect('config-parsed', app => app.Quit());
    return {};
}

export default v.ags === v.expected
    ? (await import('./js/main.js')).default
    : mismatch();
#+end_src

We then write our =package.json=, which contains some metadata on this configuration:
#+begin_src json :tangle package.json
{
    "name": "ags-config",
    "version": "1.5.5",
    "description": "AGS configuration",
    "main": "config.js",
    "author": "Dysthesis",
    "repository": {
        "type": "git",
        "url": "git+https://codeberg.org/dysthesis/nix.git"
    },
    "devDependencies": {
        "@girs/dbusmenugtk3-0.4": "^0.4.0-3.2.0",
        "@girs/gobject-2.0": "^2.76.1-3.2.3",
        "@girs/gtk-3.0": "^3.24.39-3.2.2",
        "@girs/gvc-1.0": "^1.0.0-3.1.0",
        "@girs/nm-1.0": "^1.43.1-3.1.0",
        "@typescript-eslint/eslint-plugin": "^5.33.0",
        "@typescript-eslint/parser": "^5.33.0",
        "eslint": "^8.44.0"
    }
}
#+end_src


** TSConfig
#+begin_src json :tangle tsconfig.json
{
    "compilerOptions": {
        "target": "ES2022",
        "module": "ES2022",
        "lib": [
            "ES2022"
        ],
        "allowJs": true,
        "checkJs": true,
        "strict": true,
        "noImplicitAny": false,
        "baseUrl": ".",
        "typeRoots": [
            "./types/ags.d.ts",
            "./node_modules/@girs"
        ],
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true
    }
}
#+end_src

* Structure
** JS
Contains the JavaScript files that are the skeleton of the AGS widgets.

The configurations here are [[file:./js/README.org][literate]].

*** Configurations
This directory contains the configurations for the widgets. Modifying the files here should largely suffice to change the widgets as desired.

These configurations can be found [[file:./js/config/README.org][here]].

*** Windows
This directory contains the different windows. As of right now, the following windows are available:

- [[file:./js/windows/bar/README.org][Bar]]
- [[file:./js/windows/osd/README.org][On-screen display]]
- [[./js/windows/dashboard/README.org][Dashboard]]
- [[file:./js/windows/powermenu/README.org][Power menu]]

*** Utilities
Tools to make life easier.

- [[file:./js/utils/org-agenda/README.org][Org-agenda parser]]

** SCSS
Contains stylesheets to make AGS look nicer.
